### ISSUE TITLE
Smooth Scroll for Toggle (Species)

### ISSUE THREAD

**Issue by katiemcpeak** [katiemcpeak/dsn1676-animated-website#1]
I have put a smooth scroll on the down button and the up button however when I tried to do the exact same thing for the "species" section in my navigation it will move down to where I want it to go but not smoothly. I have inserted 

$('.species').localScroll();

into the javascript and I have put 

a href="#species"

on the species button and put the 

a name="species" 

on where I want it to go. I'm not quite sure what I'm doing wrong so any suggestions would be great.

**Comment by katiemcpeak** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
`a name="species"` this isn't valid code; put an `id` on the button instead.

**Comment by katiemcpeak** [comment]
Ok, I replaced all name= with id= and I still have the same results. The down/up buttons are smooth but the species button is not.

**Comment by thomasjbradley** [comment]
``` js
$('.species').localScroll();
```

This code here is looking for something with the class of “species”; where is that on the page?

**Comment by katiemcpeak** [comment]
<li><a href="#species" class="peta gutter-half species">Species</a></li>

(I forget how to make it look like proper code on github sorry)

**Comment by katiemcpeak** [comment]
li a href="#species" class="peta gutter-half species" Species /a /li

**Comment by katiemcpeak** [comment]
```

<li><a href="#species" class="peta gutter-half species">Species</a></li>
```

**Comment by thomasjbradley** [comment]
Okay. The “species” class can't be directly on the `<a>` tag, it has to be on a parent element.

**Comment by katiemcpeak** [comment]
Okay I put it on the 

```
<li>
```

and it worked! Thanks so much!
